spring:
  application:
    name: board-app
  datasource:
    url: jdbc:mysql://localhost:3306/wisedb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
  secret-key: rlawldndWkd123!
  access-token-expire-time: 300 # 5분
  refresh-token-expire-time: 7200 # 2시간