spring:
  datasource:
    url: jdbc:h2:mem:db;MODE=MYSQL;
    username: sa
    password:
  h2:
    console:
      enabled: true
  thymeleaf:
    cache: false
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true


